(define (problem Book-Planner)
    (:domain books)
    (:objects ghost a1 a2 a3 a4 b1 b2 c1 d1 d2 d3 e1 e2 f1 f2 f3 f4 f5 g1 g2 g3 h1  - libro
              past enero febrero marzo abril mayo junio julio agosto setiembre octubre noviembre diciembre - mes
    )

    (:init 

        (anterior past enero)
        (anterior past febrero)
        (anterior past marzo)
        (anterior past abril)
        (anterior past mayo)
        (anterior past junio)
        (anterior past julio)
        (anterior past agosto)
        (anterior past setiembre)
        (anterior past octubre)
        (anterior past noviembre)
        (anterior past diciembre)
        
        (anterior enero febrero)
        (anterior enero marzo)
        (anterior enero abril)
        (anterior enero mayo)
        (anterior enero junio)
        (anterior enero julio)
        (anterior enero agosto)
        (anterior enero setiembre)
        (anterior enero octubre)
        (anterior enero noviembre)
        (anterior enero diciembre)
        (anterior febrero marzo)
        (anterior febrero abril)
        (anterior febrero mayo)
        (anterior febrero junio)
        (anterior febrero julio)
        (anterior febrero agosto)
        (anterior febrero setiembre)
        (anterior febrero octubre)
        (anterior febrero noviembre)
        (anterior febrero diciembre)
        (anterior marzo abril)
        (anterior marzo mayo)
        (anterior marzo junio)
        (anterior marzo julio)
        (anterior marzo agosto)
        (anterior marzo setiembre)
        (anterior marzo octubre)
        (anterior marzo noviembre)
        (anterior marzo diciembre)
        (anterior abril mayo)
        (anterior abril junio)
        (anterior abril julio)
        (anterior abril agosto)
        (anterior abril setiembre)
        (anterior abril octubre)
        (anterior abril noviembre)
        (anterior abril diciembre)
        (anterior mayo junio)
        (anterior mayo julio)
        (anterior mayo agosto)
        (anterior mayo setiembre)
        (anterior mayo octubre)
        (anterior mayo noviembre)
        (anterior mayo diciembre)
        (anterior junio julio)
        (anterior junio agosto)
        (anterior junio setiembre)
        (anterior junio octubre)
        (anterior junio noviembre)
        (anterior junio diciembre)
        (anterior julio agosto)
        (anterior julio setiembre)
        (anterior julio octubre)
        (anterior julio noviembre)
        (anterior julio diciembre)
        (anterior agosto setiembre)
        (anterior agosto octubre)
        (anterior agosto noviembre)
        (anterior agosto diciembre)
        (anterior setiembre octubre)
        (anterior setiembre noviembre)
        (anterior setiembre diciembre)
        (anterior octubre noviembre)
        (anterior octubre diciembre)
        (anterior noviembre diciembre)

        (anterior_directo enero febrero)
        (anterior_directo febrero marzo)
        (anterior_directo marzo abril)
        (anterior_directo abril mayo)
        (anterior_directo mayo junio)
        (anterior_directo junio julio)
        (anterior_directo julio agosto)
        (anterior_directo agosto setiembre)
        (anterior_directo setiembre octubre)
        (anterior_directo octubre noviembre)
        (anterior_directo noviembre diciembre)

        (predecesor ghost a1)
        (predecesor ghost b1)
        (predecesor ghost c1)
        (predecesor ghost d1)
        (predecesor ghost e1)
        (predecesor ghost f1)
        (predecesor ghost g1)
        (predecesor ghost h1)
        
        (predecesor a1 a2)
        (predecesor a2 a3)
        (predecesor a3 a4)

        (predecesor b1 b2)

        (predecesor d1 d2)
        (predecesor d2 d3)
        
        (predecesor e1 e2)
        
        (predecesor f1 f2)
        (predecesor f2 f3)
        (predecesor f3 f4)
        (predecesor f4 f5)

        (predecesor a4 f3)

        (predecesor g1 g2)
        (predecesor g2 g3)

        (leido ghost)
        (lee ghost past)
        
        (leido f1)
        (lee f1 past)
    )
    (:goal
        (and
            (leido f5)
        )
    )
)